/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_noisepages_nettoyeur_patchfield_csound_CsoundModule */

#ifndef _Included_com_noisepages_nettoyeur_patchfield_csound_CsoundModule
#define _Included_com_noisepages_nettoyeur_patchfield_csound_CsoundModule
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_noisepages_nettoyeur_patchfield_csound_CsoundModule
 * Method:    configureNativeComponents
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_com_noisepages_nettoyeur_patchfield_csound_CsoundModule_configureNativeComponents
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     com_noisepages_nettoyeur_patchfield_csound_CsoundModule
 * Method:    release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_noisepages_nettoyeur_patchfield_csound_CsoundModule_release
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_noisepages_nettoyeur_patchfield_csound_CsoundModule_CsoundHelper */

#ifndef _Included_com_noisepages_nettoyeur_patchfield_csound_CsoundModule_CsoundHelper
#define _Included_com_noisepages_nettoyeur_patchfield_csound_CsoundModule_CsoundHelper
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
